# Generated by Django 6.0.5 on 2026-05-17 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='billsec',
            field=models.PositiveIntegerField(default=0, help_text='Billable seconds'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='destination_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='linkedid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='source_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='disposition',
            field=models.CharField(blank=True, choices=[('ANSWERED', 'Answered'), ('NO ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('FAILED', 'Failed'), ('CANCEL', 'Cancel')], max_length=20, null=True),
        ),
    ]
