# Generated by Django 5.2.14 on 2026-06-07 10:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='asterisk_id',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='recording_path',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='secret',
        ),
        migrations.AddField(
            model_name='agent',
            name='extension',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='crm.extension'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='business_disposition',
            field=models.CharField(choices=[('PENDING', 'Pending Wrap-up'), ('SALE_CLOSED', 'Sale Closed / Deal Won'), ('INTERESTED', 'Interested / Follow-up Scheduled'), ('NOT_INTERESTED', 'Not Interested / Refused'), ('SPAM', 'Spam / Wrong Number'), ('INTERNAL_WORK', 'Internal Operations')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='calllog',
            name='wrapup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='billsec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outbound', 'Outbound'), ('internal', 'Internal')], max_length=12),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='destination_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='disposition',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='linkedid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='source_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='uniqueid',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='Normalized unique phone number string', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extension_number',
            field=models.CharField(help_text='Asterisk internal extension number', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='technology',
            field=models.CharField(choices=[('SIP', 'SIP'), ('PJSIP', 'PJSIP'), ('IAX2', 'IAX2')], default='PJSIP', max_length=10),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['phone_number', '-call_time'], name='crm_call_phone_time_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['call_type', '-call_time'], name='crm_call_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(condition=models.Q(('wrapup_completed', False)), fields=['wrapup_completed'], name='crm_call_wrapup_pending_idx'),
        ),
    ]
