# Generated by Django 5.2.14 on 2026-06-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_extension_password_alter_agent_id_alter_calllog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Historical timeline logs compiled across wrapups'),
        ),
    ]
