services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:             # <-- Tell the database to use the .env file
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python -m daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/app
      - /usr/local/lib/python3.11/site-packages/
    ports:
      - "8000:8000"
    env_file:             # <-- Tell Django to use the .env file
      - .env
    depends_on:
      - db
      - redis
      
  ami_listener:
    build: .
    command: python crm/ami_listener.py
    volumes:
      - .:/app
    restart: always
    env_file:             # <-- Tell the listener to use the .env file
      - .env
    depends_on:
      - web
      - redis

volumes:
  postgres_data: