# Generated by Django 5.2.14 on 2026-06-06 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_number', models.CharField(max_length=10, unique=True)),
                ('secret', models.CharField(max_length=100)),
                ('technology', models.CharField(default='PJSIP', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='crm.agent')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('internal', 'Internal'), ('missed', 'Missed'), ('service', 'Service / Feature Code'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('source_number', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_number', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('billsec', models.PositiveIntegerField(default=0, help_text='Billable seconds')),
                ('call_time', models.DateTimeField()),
                ('recording_file', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition', models.CharField(blank=True, choices=[('ANSWERED', 'Answered'), ('NO ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('FAILED', 'Failed'), ('CANCEL', 'Cancel')], max_length=20, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('linkedid', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asterisk_id', models.CharField(max_length=100, null=True, unique=True)),
                ('recording_path', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.agent')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.extension')),
            ],
        ),
    ]
