# Generated by Django 6.0.5 on 2026-05-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_calllog_billsec_calllog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('internal', 'Internal'), ('missed', 'Missed'), ('service', 'Service / Feature Code'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
