# Generated by Django 6.0.5 on 2026-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_calllog_call_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
