# Generated by Django 6.0.5 on 2026-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='asterisk_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='recording_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
