"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path
import os
import mimetypes

# --- CRITICAL FIX 1: Overwrite Windows-to-Container MIME registry glitches ---
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/javascript", ".js", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add this line to tell Django where to put the "collected" files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Pull the secret key from the environment, with a fallback for local dev
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-unsafe-key-for-dev')

# --- CRITICAL FIX 2: Hardcode DEBUG to True for local development ---
# This guarantees Django's internal static file server stays active.
DEBUG = True

allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost,web')
ALLOWED_HOSTS = allowed_hosts_env.split(',')


# ALLOW secure development cross-communication from React container
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'crm'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'crm_prod'),
        'USER': os.environ.get('POSTGRES_USER', 'crm_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'crm_password'),
        'HOST': 'db', 
        'PORT': '5432',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# --- CRITICAL FIX 3: Added the mandatory absolute path leading slash ---
STATIC_URL = '/static/'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)], 
        },
    },
}

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Asterisk AMI Settings
AMI_HOST = os.environ.get('AMI_HOST', '192.168.100.115')
AMI_PORT = int(os.environ.get('AMI_PORT', 5038))
AMI_USER = os.environ.get('AMI_USER', 'django_crm')
AMI_PASS = os.environ.get('AMI_PASS', '')


# Issabel DB Settings (for custom management commands)
PBX_DB_HOST = os.environ.get('PBX_DB_HOST', '192.168.100.115')
PBX_DB_PORT = int(os.environ.get('PBX_DB_PORT', 3306))
PBX_DB_NAME = os.environ.get('PBX_DB_NAME', 'asteriskcdrdb')
PBX_DB_USER = os.environ.get('PBX_DB_USER', 'crm_reader')
PBX_DB_PASS = os.environ.get('PBX_DB_PASS', 'Admin1234')

# Issabel SSH/SFTP Settings (for secure on-demand streaming of call recording audio)
PBX_SSH_HOST = os.environ.get('PBX_SSH_HOST', '192.168.100.115')
PBX_SSH_PORT = int(os.environ.get('PBX_SSH_PORT', 22))
PBX_SSH_USER = os.environ.get('PBX_SSH_USER', 'admin')
PBX_SSH_PASS = os.environ.get('PBX_SSH_PASS', '')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CRITICAL: Allow session cookies to pass through cross-origin API fetches
CORS_ALLOW_CREDENTIALS = True